# Generated by Django 2.1.2 on 2018-10-27 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, help_text='Codigo Unico de la Mascota', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre Mascota', max_length=30)),
                ('tamanio', models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], default='SI', help_text='Tamaño de la Mascota', max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en Kg de la Mascota', max_digits=4)),
                ('color', models.CharField(help_text='Color de la Mascota', max_length=30)),
                ('estado', models.CharField(choices=[('SI', 'Adoptado'), ('NO', 'Sin Adoptar')], default='SI', help_text='Seleccione estado de la Mascota', max_length=2)),
                ('descripcion', models.CharField(help_text='Descripcion de la Mascota', max_length=30)),
            ],
        ),
    ]
