# Generated by Django 2.1.2 on 2018-10-27 17:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misperris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='adoptante',
            field=models.ForeignKey(blank=True, help_text='Persona que adopta', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecharescate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('Rescatado', '1'), ('Disponible', '2'), ('Adoptado', '3')], default='Rescatado', help_text='Seleccione estado de la Mascota', max_length=2),
        ),
    ]
