# Generated by Django 2.1.2 on 2018-10-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0002_auto_20181027_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('1', 'Rescatado'), ('2', 'Disponible'), ('3', 'Adoptado')], default='Rescatado', help_text='Seleccione estado de la Mascota', max_length=2),
        ),
    ]
